version: "3.9"
services:
    web:
        #image: php:8.0-apache
        ports:
            - "80:80"
        volumes:
            - ./php:/var/www/html
        depends_on:
            - db
        restart: always
        build: 
            context: .
            dockerfile: Dockerfile

    db:
        container_name: phpDB
        hostname: dev-postgres
        image: postgres
        restart: always
        env_file:
            - ./env/database.env
        volumes:
            - data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - ./env/pgadmin.env
        ports:
            - "8081:80"
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
        - db

volumes:
        data:
        pgadmin:
